/* =====================================================================
   Gitignore Generator Pro — app.js
   Fully offline. All templates are static string literals baked into
   this file — no network calls, no dependency on github/gitignore or
   gitignore.io.
   ===================================================================== */
(function () {
  'use strict';

  /* =================================================================
     TEMPLATE LIBRARY
     Each stack: id, name, group, content (raw .gitignore text).
     Grouped in display order: Languages & Runtimes, Frameworks &
     Engines, Editors & IDEs, Operating Systems, DevOps,
     Environment & Secrets.
     ================================================================= */
  var STACKS = [
    // ---------------- Languages & Runtimes ----------------
    {
      id: 'node', name: 'Node.js', group: 'Languages & Runtimes',
      content:
'node_modules/\n' +
'jspm_packages/\n' +
'\n' +
'# Package manager logs\n' +
'npm-debug.log*\n' +
'yarn-debug.log*\n' +
'yarn-error.log*\n' +
'pnpm-debug.log*\n' +
'lerna-debug.log*\n' +
'\n' +
'# Build output\n' +
'dist/\n' +
'build/\n' +
'out/\n' +
'.cache/\n' +
'.parcel-cache/\n' +
'\n' +
'# Coverage\n' +
'coverage/\n' +
'.nyc_output/\n' +
'\n' +
'# Misc\n' +
'*.tsbuildinfo\n' +
'.eslintcache'
    },
    {
      id: 'python', name: 'Python', group: 'Languages & Runtimes',
      content:
'__pycache__/\n' +
'*.py[cod]\n' +
'*$py.class\n' +
'\n' +
'# Distribution / packaging\n' +
'build/\n' +
'dist/\n' +
'*.egg-info/\n' +
'.eggs/\n' +
'*.egg\n' +
'\n' +
'# Virtual environments\n' +
'.venv/\n' +
'venv/\n' +
'env/\n' +
'ENV/\n' +
'\n' +
'# Testing\n' +
'.pytest_cache/\n' +
'.tox/\n' +
'.coverage\n' +
'.coverage.*\n' +
'htmlcov/\n' +
'nosetests.xml\n' +
'coverage.xml\n' +
'\n' +
'# Type checkers\n' +
'.mypy_cache/\n' +
'.pyre/\n' +
'.pytype/\n' +
'\n' +
'# Jupyter\n' +
'.ipynb_checkpoints/'
    },
    {
      id: 'java', name: 'Java', group: 'Languages & Runtimes',
      content:
'*.class\n' +
'*.log\n' +
'\n' +
'# Build tools\n' +
'target/\n' +
'build/\n' +
'out/\n' +
'.gradle/\n' +
'gradle-app.setting\n' +
'!gradle-wrapper.jar\n' +
'\n' +
'# Packaged archives\n' +
'*.jar\n' +
'*.war\n' +
'*.ear\n' +
'\n' +
'# JVM crash logs\n' +
'hs_err_pid*\n' +
'replay_pid*'
    },
    {
      id: 'go', name: 'Go', group: 'Languages & Runtimes',
      content:
'# Binaries\n' +
'*.exe\n' +
'*.exe~\n' +
'*.dll\n' +
'*.so\n' +
'*.dylib\n' +
'\n' +
'# Test binaries\n' +
'*.test\n' +
'\n' +
'# Coverage output\n' +
'*.out\n' +
'\n' +
'# Dependency directories\n' +
'vendor/\n' +
'\n' +
'# Go workspace files\n' +
'go.work\n' +
'go.work.sum\n' +
'\n' +
'# Build output\n' +
'/bin/\n' +
'/dist/'
    },
    {
      id: 'rust', name: 'Rust', group: 'Languages & Runtimes',
      content:
'# Generated by Cargo\n' +
'/target/\n' +
'**/*.rs.bk\n' +
'\n' +
'# Uncomment if this is a library and you do not want to commit the lockfile\n' +
'# Cargo.lock\n' +
'\n' +
'*.pdb'
    },
    {
      id: 'cpp', name: 'C/C++ (CMake)', group: 'Languages & Runtimes',
      content:
'# Build directories\n' +
'build/\n' +
'cmake-build-*/\n' +
'out/\n' +
'\n' +
'# CMake generated files\n' +
'CMakeCache.txt\n' +
'CMakeFiles/\n' +
'CMakeScripts/\n' +
'Testing/\n' +
'cmake_install.cmake\n' +
'install_manifest.txt\n' +
'compile_commands.json\n' +
'CTestTestfile.cmake\n' +
'_deps/\n' +
'\n' +
'# Object files\n' +
'*.o\n' +
'*.obj\n' +
'*.lo\n' +
'*.slo\n' +
'\n' +
'# Precompiled headers\n' +
'*.gch\n' +
'*.pch\n' +
'\n' +
'# Libraries\n' +
'*.a\n' +
'*.la\n' +
'*.lai\n' +
'*.lib\n' +
'*.so\n' +
'*.so.*\n' +
'*.dylib\n' +
'*.dll\n' +
'\n' +
'# Executables\n' +
'*.exe\n' +
'*.out\n' +
'*.app'
    },
    {
      id: 'ruby', name: 'Ruby', group: 'Languages & Runtimes',
      content:
'*.gem\n' +
'*.rbc\n' +
'/.config\n' +
'/coverage/\n' +
'/InstalledFiles\n' +
'/pkg/\n' +
'/spec/reports/\n' +
'/spec/examples.txt\n' +
'/test/tmp/\n' +
'/test/version_tmp/\n' +
'/tmp/\n' +
'\n' +
'# Bundler\n' +
'/.bundle/\n' +
'/vendor/bundle\n' +
'/lib/bundler/man/\n' +
'\n' +
'# RVM\n' +
'.rvmrc\n' +
'\n' +
'# RSpec\n' +
'.rspec_status'
    },
    {
      id: 'php', name: 'PHP', group: 'Languages & Runtimes',
      content:
'/vendor/\n' +
'composer.phar\n' +
'\n' +
'# Framework cache/logs (adjust paths for your framework)\n' +
'/storage/*.key\n' +
'/storage/logs/*.log\n' +
'/bootstrap/cache/*\n' +
'\n' +
'# Testing\n' +
'.phpunit.result.cache\n' +
'.phpunit.cache/'
    },
    {
      id: 'dotnet', name: '.NET / Visual Studio', group: 'Languages & Runtimes',
      content:
'bin/\n' +
'obj/\n' +
'*.user\n' +
'*.suo\n' +
'*.userosscache\n' +
'*.sln.docstates\n' +
'\n' +
'# Build results\n' +
'[Dd]ebug/\n' +
'[Rr]elease/\n' +
'x64/\n' +
'x86/\n' +
'[Bb]uild/\n' +
'\n' +
'# Visual Studio cache/options\n' +
'.vs/\n' +
'*.pidb\n' +
'*.svclog\n' +
'\n' +
'# NuGet\n' +
'*.nupkg\n' +
'**/packages/*\n' +
'!**/packages/build/\n' +
'\n' +
'# Test results\n' +
'[Tt]est[Rr]esult*/'
    },
    {
      id: 'elixir', name: 'Elixir', group: 'Languages & Runtimes',
      content:
'/_build/\n' +
'/cover/\n' +
'/deps/\n' +
'/doc/\n' +
'/.fetch\n' +
'erl_crash.dump\n' +
'*.ez\n' +
'*.beam\n' +
'\n' +
'# Mix secrets\n' +
'/config/*.secret.exs\n' +
'\n' +
'# Dialyzer\n' +
'/priv/plts/*.plt\n' +
'/priv/plts/*.plt.hash'
    },
    {
      id: 'android', name: 'Android', group: 'Languages & Runtimes',
      content:
'*.apk\n' +
'*.aab\n' +
'*.ap_\n' +
'*.dex\n' +
'\n' +
'# Build\n' +
'/build/\n' +
'/*/build/\n' +
'/captures/\n' +
'.gradle/\n' +
'local.properties\n' +
'\n' +
'# IDE\n' +
'*.iml\n' +
'\n' +
'# Keystores\n' +
'*.jks\n' +
'*.keystore'
    },
    {
      id: 'xcode', name: 'Xcode / Swift', group: 'Languages & Runtimes',
      content:
'# Xcode\n' +
'build/\n' +
'DerivedData/\n' +
'*.xcuserstate\n' +
'*.xcuserdatad/\n' +
'*.xcscmblueprint\n' +
'*.xccheckout\n' +
'xcuserdata/\n' +
'*.moved-aside\n' +
'*.pbxuser\n' +
'*.perspectivev3\n' +
'\n' +
'# Swift Package Manager\n' +
'.build/\n' +
'Packages/\n' +
'Package.resolved\n' +
'\n' +
'# CocoaPods\n' +
'Pods/\n' +
'\n' +
'# Carthage\n' +
'Carthage/Build/\n' +
'\n' +
'# fastlane\n' +
'fastlane/report.xml\n' +
'fastlane/Preview.html\n' +
'fastlane/screenshots/**/*.png\n' +
'fastlane/test_output'
    },
    {
      id: 'flutter', name: 'Flutter / Dart', group: 'Languages & Runtimes',
      content:
'.dart_tool/\n' +
'.flutter-plugins\n' +
'.flutter-plugins-dependencies\n' +
'.pub-cache/\n' +
'.pub/\n' +
'/build/\n' +
'\n' +
'# Generated docs\n' +
'**/doc/api/\n' +
'\n' +
'# Generated plugin registrant\n' +
'lib/generated_plugin_registrant.dart\n' +
'\n' +
'# Symbolication\n' +
'app.*.symbols\n' +
'\n' +
'# Misc\n' +
'migrate_working_dir/'
    },

    // ---------------- Frameworks & Engines ----------------
    {
      id: 'unity', name: 'Unity', group: 'Frameworks & Engines',
      content:
'[Ll]ibrary/\n' +
'[Tt]emp/\n' +
'[Oo]bj/\n' +
'[Bb]uild/\n' +
'[Bb]uilds/\n' +
'[Ll]ogs/\n' +
'[Uu]ser[Ss]ettings/\n' +
'\n' +
'# Never ignore asset meta data\n' +
'!/[Aa]ssets/**/*.meta\n' +
'\n' +
'# Autogenerated VS/MD/Consulo solution and project files\n' +
'ExportedObj/\n' +
'.consulo/\n' +
'*.csproj\n' +
'*.unityproj\n' +
'*.sln\n' +
'*.suo\n' +
'*.tmp\n' +
'*.user\n' +
'*.userprefs\n' +
'*.pidb\n' +
'*.booproj\n' +
'*.svd\n' +
'*.pdb\n' +
'*.mdb\n' +
'*.opendb\n' +
'*.VC.db\n' +
'\n' +
'# Unity3D generated meta files\n' +
'*.pidb.meta\n' +
'*.pdb.meta\n' +
'*.mdb.meta\n' +
'\n' +
'# Crash reports\n' +
'sysinfo.txt\n' +
'\n' +
'# Builds\n' +
'*.apk\n' +
'*.unitypackage\n' +
'\n' +
'# Crashlytics\n' +
'crashlytics-build.properties'
    },
    {
      id: 'godot', name: 'Godot', group: 'Frameworks & Engines',
      content:
'# Godot 4+ specific ignores\n' +
'.godot/\n' +
'.import/\n' +
'\n' +
'# Imported translations (generated from CSV files)\n' +
'*.translation\n' +
'\n' +
'# Mono-specific ignores\n' +
'.mono/\n' +
'data_*/\n' +
'mono_crash.*.json\n' +
'\n' +
'# System/tool specific ignores\n' +
'.directory\n' +
'*.import\n' +
'\n' +
'# Exported files\n' +
'export.cfg\n' +
'export_presets.cfg\n' +
'\n' +
'# NOTE: export_presets.cfg can contain sensitive export credentials\n' +
'# (e.g. keystore paths/passwords). Review before committing it instead\n' +
'# of ignoring it.'
    },
    {
      id: 'nextjs', name: 'Next.js / React', group: 'Frameworks & Engines',
      content:
'.next/\n' +
'out/\n' +
'.vercel/\n' +
'.turbo/\n' +
'next-env.d.ts\n' +
'\n' +
'# Create React App build output\n' +
'/build/\n' +
'\n' +
'# Testing\n' +
'/coverage/'
    },

    // ---------------- Editors & IDEs ----------------
    {
      id: 'vscode', name: 'VS Code', group: 'Editors & IDEs',
      content:
'.vscode/*\n' +
'!.vscode/settings.json\n' +
'!.vscode/tasks.json\n' +
'!.vscode/launch.json\n' +
'!.vscode/extensions.json\n' +
'*.code-workspace\n' +
'\n' +
'# Local History extension\n' +
'.history/'
    },
    {
      id: 'jetbrains', name: 'JetBrains / IntelliJ', group: 'Editors & IDEs',
      content:
'.idea/\n' +
'*.iml\n' +
'*.ipr\n' +
'*.iws\n' +
'.idea_modules/\n' +
'cmake-build-*/'
    },
    {
      id: 'sublime', name: 'Sublime Text', group: 'Editors & IDEs',
      content:
'*.sublime-workspace\n' +
'*.sublime-project\n' +
'\n' +
'# SFTP configuration\n' +
'sftp-config.json\n' +
'sftp-config-alt*.json\n' +
'\n' +
'# Package Control\n' +
'Package Control.last-run\n' +
'Package Control.ca-list\n' +
'Package Control.ca-bundle\n' +
'Package Control.system-ca-bundle\n' +
'Package Control.cache/\n' +
'Package Control.ca-certs/\n' +
'Package Control.merged-ca-bundle\n' +
'Package Control.user-ca-bundle\n' +
'oscrypto-ca-bundle.crt\n' +
'bh_unicode_properties.cache\n' +
'\n' +
'GitHub.sublime-settings'
    },
    {
      id: 'vim', name: 'Vim / Emacs (swap files)', group: 'Editors & IDEs',
      content:
'# Vim\n' +
'*.swp\n' +
'*.swo\n' +
'*.swn\n' +
'*~\n' +
'.netrwhist\n' +
'Session.vim\n' +
'.viminfo\n' +
'\n' +
'# Emacs\n' +
'\\#*\\#\n' +
'.\\#*\n' +
'.emacs.desktop\n' +
'.emacs.desktop.lock\n' +
'*.elc\n' +
'auto-save-list\n' +
'tramp'
    },

    // ---------------- Operating Systems ----------------
    {
      id: 'macos', name: 'macOS', group: 'Operating Systems',
      content:
'.DS_Store\n' +
'.AppleDouble\n' +
'.LSOverride\n' +
'Icon?\n' +
'\n' +
'._*\n' +
'.DocumentRevisions-V100\n' +
'.fseventsd\n' +
'.Spotlight-V100\n' +
'.TemporaryItems\n' +
'.Trashes\n' +
'.VolumeIcon.icns\n' +
'.com.apple.timemachine.donotpresent\n' +
'\n' +
'# Directories potentially created on remote AFP share\n' +
'.AppleDB\n' +
'.AppleDesktop\n' +
'Network Trash Folder\n' +
'Temporary Items\n' +
'.apdisk'
    },
    {
      id: 'windows', name: 'Windows', group: 'Operating Systems',
      content:
'Thumbs.db\n' +
'Thumbs.db:encryptable\n' +
'ehthumbs.db\n' +
'ehthumbs_vista.db\n' +
'*.stackdump\n' +
'[Dd]esktop.ini\n' +
'$RECYCLE.BIN/\n' +
'*.cab\n' +
'*.msi\n' +
'*.msix\n' +
'*.msm\n' +
'*.msp\n' +
'*.lnk'
    },
    {
      id: 'linux', name: 'Linux', group: 'Operating Systems',
      content:
'*~\n' +
'.fuse_hidden*\n' +
'.directory\n' +
'.Trash-*\n' +
'.nfs*'
    },

    // ---------------- DevOps ----------------
    {
      id: 'docker', name: 'Docker', group: 'DevOps',
      content:
'# Local compose overrides\n' +
'docker-compose.override.yml\n' +
'docker-compose.override.yaml\n' +
'\n' +
'# Local Docker config/data\n' +
'.docker/\n' +
'\n' +
'# Environment files used for local compose runs\n' +
'.env.docker'
    },
    {
      id: 'terraform', name: 'Terraform', group: 'DevOps',
      content:
'# Local .terraform directories\n' +
'**/.terraform/*\n' +
'\n' +
'# .tfstate files\n' +
'*.tfstate\n' +
'*.tfstate.*\n' +
'\n' +
'# Crash log files\n' +
'crash.log\n' +
'crash.*.log\n' +
'\n' +
'# Override files\n' +
'override.tf\n' +
'override.tf.json\n' +
'*_override.tf\n' +
'*_override.tf.json\n' +
'\n' +
'# CLI configuration files\n' +
'.terraformrc\n' +
'terraform.rc\n' +
'\n' +
'# Variable files that may contain sensitive data\n' +
'*.tfvars\n' +
'*.tfvars.json'
    },

    // ---------------- Environment & Secrets ----------------
    {
      id: 'envsecrets', name: 'Environment & Secrets', group: 'Environment & Secrets',
      content:
'.env\n' +
'.env.local\n' +
'.env.*.local\n' +
'.env.development\n' +
'.env.production\n' +
'.env.test\n' +
'\n' +
'# Logs\n' +
'*.log\n' +
'logs/\n' +
'\n' +
'# Keys/certs\n' +
'*.pem\n' +
'*.key\n' +
'secrets.*\n' +
'!secrets.example.*'
    }
  ];

  var GROUP_ORDER = ['Languages & Runtimes', 'Frameworks & Engines', 'Editors & IDEs', 'Operating Systems', 'DevOps', 'Environment & Secrets'];

  var STORE_KEY = 'gitignoreSelection';

  /* =================================================================
     STATE
     ================================================================= */
  var selected = {}; // id -> true

  /* =================================================================
     DOM REFS
     ================================================================= */
  var stackGroupsEl = document.getElementById('stackGroups');
  var noResultsEl = document.getElementById('noResults');
  var searchInput = document.getElementById('searchInput');
  var outputEl = document.getElementById('output');
  var emptyStateEl = document.getElementById('emptyState');
  var outputStatsEl = document.getElementById('outputStats');
  var pickerStatsEl = document.getElementById('pickerStats');
  var statusBadge = document.getElementById('statusBadge');
  var statusText = document.getElementById('statusText');

  /* =================================================================
     BUILD PICKER UI
     ================================================================= */
  function buildPicker() {
    var groups = {};
    STACKS.forEach(function (s) {
      if (!groups[s.group]) groups[s.group] = [];
      groups[s.group].push(s);
    });

    var html = '';
    GROUP_ORDER.forEach(function (groupName) {
      var stacks = groups[groupName];
      if (!stacks || !stacks.length) return;
      html += '<div class="stack-group" data-group="' + WUS.escapeHtml(groupName) + '">';
      html += '<h3 class="stack-group-title">' + WUS.escapeHtml(groupName) + '</h3>';
      html += '<div class="stack-grid">';
      stacks.forEach(function (s) {
        html += '<label class="stack-item" data-id="' + s.id + '" data-name="' + WUS.escapeHtml(s.name.toLowerCase()) + '">' +
          '<input type="checkbox" data-id="' + s.id + '" aria-label="' + WUS.escapeHtml(s.name) + '">' +
          '<span class="stack-item-label">' + WUS.escapeHtml(s.name) + '</span>' +
          '</label>';
      });
      html += '</div></div>';
    });
    stackGroupsEl.innerHTML = html;

    // Wire checkbox + row click events.
    var items = stackGroupsEl.querySelectorAll('.stack-item');
    items.forEach(function (item) {
      var cb = item.querySelector('input[type="checkbox"]');
      cb.addEventListener('change', function () {
        toggleStack(cb.getAttribute('data-id'), cb.checked);
      });
    });
  }

  function toggleStack(id, on) {
    if (on) selected[id] = true;
    else delete selected[id];
    syncItemVisualState(id, on);
    renderOutput();
    updateStatus();
    persist();
  }

  function syncItemVisualState(id, on) {
    var item = stackGroupsEl.querySelector('.stack-item[data-id="' + id + '"]');
    if (item) item.classList.toggle('is-checked', !!on);
  }

  function setAllChecked(on) {
    STACKS.forEach(function (s) {
      if (on) selected[s.id] = true;
      else delete selected[s.id];
    });
    var boxes = stackGroupsEl.querySelectorAll('input[type="checkbox"]');
    boxes.forEach(function (cb) {
      cb.checked = on;
      syncItemVisualState(cb.getAttribute('data-id'), on);
    });
    renderOutput();
    updateStatus();
    persist();
  }

  /* =================================================================
     SEARCH / FILTER
     ================================================================= */
  function applyFilter() {
    var q = searchInput.value.trim().toLowerCase();
    var groupEls = stackGroupsEl.querySelectorAll('.stack-group');
    var anyVisible = false;

    groupEls.forEach(function (groupEl) {
      var items = groupEl.querySelectorAll('.stack-item');
      var groupHasVisible = false;
      items.forEach(function (item) {
        var name = item.getAttribute('data-name') || '';
        var match = !q || name.indexOf(q) > -1;
        item.hidden = !match;
        if (match) { groupHasVisible = true; anyVisible = true; }
      });
      groupEl.hidden = !groupHasVisible;
    });

    noResultsEl.hidden = anyVisible;
  }

  /* =================================================================
     MERGE / DE-DUPLICATE LOGIC
     ================================================================= */
  function buildOutput() {
    var emitted = {};
    var out = [];

    STACKS.forEach(function (stack) {
      if (!selected[stack.id]) return;

      var lines = stack.content.split('\n');
      var blockLines = [];
      var addedPattern = false;

      lines.forEach(function (line) {
        var trimmed = line.trim();
        if (trimmed === '') { blockLines.push(''); return; }
        if (trimmed.charAt(0) === '#') { blockLines.push(line); return; }
        if (emitted[trimmed]) return; // already covered by an earlier-selected stack
        emitted[trimmed] = true;
        blockLines.push(line);
        addedPattern = true;
      });

      if (!addedPattern) return; // stack contributed nothing new; omit header + block entirely

      // Trim leading/trailing blank lines within the block for tidy output.
      while (blockLines.length && blockLines[0].trim() === '') blockLines.shift();
      while (blockLines.length && blockLines[blockLines.length - 1].trim() === '') blockLines.pop();

      out.push('# ==== ' + stack.name + ' ====');
      out.push.apply(out, blockLines);
      out.push('');
    });

    while (out.length && out[out.length - 1] === '') out.pop();
    return out.join('\n');
  }

  function renderOutput() {
    var text = buildOutput();
    outputEl.textContent = text;
    var hasText = text.length > 0;
    emptyStateEl.classList.toggle('is-hidden', hasText);
    var lineCount = hasText ? text.split('\n').length : 0;
    outputStatsEl.textContent = lineCount + (lineCount === 1 ? ' line' : ' lines');
  }

  function updateStatus() {
    var count = Object.keys(selected).length;
    statusText.textContent = count + (count === 1 ? ' selected' : ' selected');
    statusBadge.classList.toggle('has-selection', count > 0);
    pickerStatsEl.textContent = count + ' / ' + STACKS.length + ' selected';
  }

  /* =================================================================
     PERSISTENCE
     ================================================================= */
  function persist() {
    WUS.store.set(STORE_KEY, Object.keys(selected));
  }

  function restore() {
    var saved = WUS.store.get(STORE_KEY, null);
    if (!saved || !Array.isArray(saved)) return;
    var validIds = {};
    STACKS.forEach(function (s) { validIds[s.id] = true; });
    saved.forEach(function (id) {
      if (!validIds[id]) return;
      selected[id] = true;
      var cb = stackGroupsEl.querySelector('input[type="checkbox"][data-id="' + id + '"]');
      if (cb) cb.checked = true;
      syncItemVisualState(id, true);
    });
  }

  /* =================================================================
     COPY / DOWNLOAD
     ================================================================= */
  function currentOutputText() {
    return outputEl.textContent || '';
  }

  function copyOutput() {
    var text = currentOutputText();
    if (!text) { WUS.toast('Select at least one stack first', 'error'); return; }
    WUS.copy(text, 'Copied .gitignore to clipboard');
  }

  function downloadOutput() {
    var text = currentOutputText();
    if (!text) { WUS.toast('Select at least one stack first', 'error'); return; }
    WUS.download('.gitignore', text, 'text/plain;charset=utf-8');
    WUS.toast('Downloaded .gitignore');
  }

  /* =================================================================
     SHORTCUTS HELP MODAL
     ================================================================= */
  var helpBackdrop = document.getElementById('helpBackdrop');
  var helpClose = document.getElementById('helpClose');
  var shortcutRows = document.getElementById('shortcutRows');

  var SHORTCUTS = [
    { keys: ['mod', 'C'], desc: 'Copy merged .gitignore' },
    { keys: ['mod', 'S'], desc: 'Download .gitignore' },
    { keys: ['?'], desc: 'Show this help' },
    { keys: ['Esc'], desc: 'Close dialog' }
  ];

  function buildShortcutTable() {
    var html = '';
    SHORTCUTS.forEach(function (s) {
      var kbds = s.keys.map(function (k) { return '<kbd>' + WUS.escapeHtml(k) + '</kbd>'; }).join('');
      html += '<tr><td>' + WUS.escapeHtml(s.desc) + '</td><td>' + kbds + '</td></tr>';
    });
    shortcutRows.innerHTML = html;
  }

  function openHelp() { helpBackdrop.hidden = false; helpClose.focus(); }
  function closeHelp() { helpBackdrop.hidden = true; }

  helpClose.addEventListener('click', closeHelp);
  helpBackdrop.addEventListener('click', function (e) {
    if (e.target === helpBackdrop) closeHelp();
  });
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape' && !helpBackdrop.hidden) closeHelp();
  });

  var helpBtns = document.querySelectorAll('[data-shortcut-help]');
  for (var i = 0; i < helpBtns.length; i++) helpBtns[i].addEventListener('click', openHelp);

  /* =================================================================
     WIRING
     ================================================================= */
  document.getElementById('btnSelectAll').addEventListener('click', function () { setAllChecked(true); });
  document.getElementById('btnClearAll').addEventListener('click', function () { setAllChecked(false); });
  document.getElementById('btnCopy').addEventListener('click', copyOutput);
  document.getElementById('btnDownload').addEventListener('click', downloadOutput);
  searchInput.addEventListener('input', WUS.debounce(applyFilter, 80));

  WUS.registerShortcut('mod+c', copyOutput, 'Copy merged .gitignore');
  WUS.registerShortcut('mod+s', downloadOutput, 'Download .gitignore');
  WUS.registerShortcut('?', openHelp, 'Show this help');

  /* =================================================================
     INIT
     ================================================================= */
  buildPicker();
  restore();
  applyFilter();
  renderOutput();
  updateStatus();
  buildShortcutTable();
})();
